create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null unique
    check (username ~ '^[A-Za-z0-9_]{3,20}$'),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  image_url text not null,
  caption text not null default '',
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx
  on public.posts (created_at desc);

create index if not exists posts_likes_idx
  on public.posts (likes desc);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;

grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select on public.posts to anon, authenticated;
grant insert on public.posts to authenticated;

drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public"
  on public.profiles for select
  using (true);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile"
  on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "Posts are public" on public.posts;
create policy "Posts are public"
  on public.posts for select
  using (true);

drop policy if exists "Users can create their own posts" on public.posts;
create policy "Users can create their own posts"
  on public.posts for insert to authenticated
  with check ((select auth.uid()) = user_id);

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_username text;
begin
  profile_username := lower(coalesce(new.raw_user_meta_data ->> 'username', ''));

  if profile_username !~ '^[a-z0-9_]{3,20}$' then
    profile_username := 'user_' || left(replace(new.id::text, '-', ''), 12);
  end if;

  insert into public.profiles (id, username)
  values (new.id, profile_username);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute procedure public.create_profile_for_new_user();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'supagram',
  'supagram',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Supagram files are publicly readable" on storage.objects;
create policy "Supagram files are publicly readable"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'supagram');

drop policy if exists "Users can upload their own Supagram files" on storage.objects;
create policy "Users can upload their own Supagram files"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'supagram'
    and (storage.foldername(name))[1] in ('images', 'profile')
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );

drop policy if exists "Users can update their own Supagram files" on storage.objects;
create policy "Users can update their own Supagram files"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'supagram'
    and (storage.foldername(name))[1] in ('images', 'profile')
    and (storage.foldername(name))[2] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'supagram'
    and (storage.foldername(name))[1] in ('images', 'profile')
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );

drop policy if exists "Users can delete their own Supagram files" on storage.objects;
create policy "Users can delete their own Supagram files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'supagram'
    and (storage.foldername(name))[1] in ('images', 'profile')
    and (storage.foldername(name))[2] = (select auth.uid())::text
  );
